version: '3'
services:
  whatsapp-bot-dev:
    build:
      context: .
      dockerfile: Dockerfile
    command: ['npm', 'run', 'dev']
    environment:
      CHAT_NAME: ${CHAT_NAME}
    volumes:
      # - .:/app
      - ./src:/app/src
      - ./logs:/app/logs
      - ./external:/app/external
      - ./package.json:/app/package.json
      - ./.env:/app/.env
      - ./tsconfig.json:/app/tsconfig.json
      - .gcp:/app/.gcp
